import type { RequestPayloadMap } from "./payloads";

export type RequestType = "json" | "formData" | "urlencoded" | "raw";

export type EndpointDef = {
  path: string;
  method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
  responseType: string;
  requestType: RequestType | null;
  payloadType: keyof RequestPayloadMap | null;
};

export const ENDPOINTS = {
  getCategories: {
    path: "/api/api/categorias/",
    method: "GET",
    responseType: "CategoryListResponse",
    requestType: null,
    payloadType: null,
  },
  createCategory: {
    path: "/api/api/categorias/",
    method: "POST",
    responseType: "CategoryResponse",
    requestType: "json",
    payloadType: "CreateCategory",
  },
  updateCategory: {
    path: "/api/api/categorias/:id/",
    method: "PATCH",
    responseType: "CategoryResponse",
    requestType: "json",
    payloadType: "UpdateCategory",
  },
  deleteCategory: {
    path: "/api/api/categorias/:id/",
    method: "DELETE",
    responseType: "DeleteResponse",
    requestType: null,
    payloadType: null,
  },
  updateUserFMCToken: {
    path: "/fcmtoken",
    method: "DELETE",
    responseType: "DeleteResponse",
    requestType: null,
    payloadType: null,
  },


  // Users
    getUsers: {
        path: "/api/api/usuarios/",
        method: "GET",
        responseType: "UserList",
        requestType: null,
        payloadType: null,
    },
    createUser: {
        path: "/api/api/usuarios/",
        method: "POST",
        responseType: "UserWrite",
        requestType: "json",
        payloadType: "CreateUser",
    },
    getUserById: {
        path: "/api/api/usuarios/:id/",
        method: "GET",
        responseType: "User",
        requestType: null,
        payloadType: null,
    },
    replaceUser: {
        path: "/api/api/usuarios/:id/",
        method: "PUT",
        responseType: "UserWrite",
        requestType: "json",
        payloadType: "ReplaceUser",
    },
    updateUser: {
        path: "/api/api/usuarios/:id/",
        method: "PATCH",
        responseType: "UserWrite",
        requestType: "json",
        payloadType: "UpdateUser",
    },
    deleteUser: {
        path: "/api/api/usuarios/:id/",
        method: "DELETE",
        responseType: "DeleteResponse",
        requestType: null,
        payloadType: null,
    },
    changeUserPassword: {
        path: "/api/api/usuarios/:id/cambiar_password/",
        method: "POST",
        responseType: "User",
        requestType: "json",
        payloadType: "ChangeUserPassword",
    },
    getMyProfile: {
        path: "/api/api/usuarios/me/",
        method: "GET",
        responseType: "User",
        requestType: null,
        payloadType: null,
    },

    // Case-Category relation
    getCaseCategoryRelations: {
        path: "/api/api/caso-categorias/",
        method: "GET",
        responseType: "CaseCategoryRelationList",
        requestType: null,
        payloadType: null,
    },
    createCaseCategoryRelation: {
        path: "/api/api/caso-categorias/",
        method: "POST",
        responseType: "CaseCategoryRelation",
        requestType: "json",
        payloadType: "CreateCaseCategoryRelation",
    },
    getCaseCategoryRelationById: {
        path: "/api/api/caso-categorias/:id/",
        method: "GET",
        responseType: "CaseCategoryRelation",
        requestType: null,
        payloadType: null,
    },
    replaceCaseCategoryRelation: {
        path: "/api/api/caso-categorias/:id/",
        method: "PUT",
        responseType: "CaseCategoryRelation",
        requestType: "json",
        payloadType: "ReplaceCaseCategoryRelation",
    },
    updateCaseCategoryRelation: {
        path: "/api/api/caso-categorias/:id/",
        method: "PATCH",
        responseType: "CaseCategoryRelation",
        requestType: "json",
        payloadType: "UpdateCaseCategoryRelation",
    },
    deleteCaseCategoryRelation: {
        path: "/api/api/caso-categorias/:id/",
        method: "DELETE",
        responseType: "DeleteResponse",
        requestType: null,
        payloadType: null,
    },

    // Cases
    getCases: {
        path: "/api/api/casos/",
        method: "GET",
        responseType: "CaseList",
        requestType: null,
        payloadType: null,
    },
    createCase: {
        path: "/api/api/casos/",
        method: "POST",
        responseType: "CaseWrite",
        requestType: "json",
        payloadType: "CreateCase",
    },
    getCaseById: {
        path: "/api/api/casos/:id/",
        method: "GET",
        responseType: "Case",
        requestType: null,
        payloadType: null,
    },
    replaceCase: {
        path: "/api/api/casos/:id/",
        method: "PUT",
        responseType: "CaseWrite",
        requestType: "json",
        payloadType: "ReplaceCase",
    },
    updateCase: {
        path: "/api/api/casos/:id/",
        method: "PATCH",
        responseType: "CaseWrite",
        requestType: "json",
        payloadType: "UpdateCase",
    },
    deleteCase: {
        path: "/api/api/casos/:id/",
        method: "DELETE",
        responseType: "DeleteResponse",
        requestType: null,
        payloadType: null,
    },
    getCaseStats: {
        path: "/api/api/casos/estadisticas/",
        method: "GET",
        responseType: "CaseStats",
        requestType: null,
        payloadType: null,
    },
    getCaseMap: {
        path: "/api/api/casos/mapa/",
        method: "GET",
        responseType: "CaseMapList",
        requestType: null,
        payloadType: null,
    },

    // Donations
    getDonations: {
        path: "/api/api/donaciones/",
        method: "GET",
        responseType: "DonationList",
        requestType: null,
        payloadType: null,
    },
    createDonation: {
        path: "/api/api/donaciones/",
        method: "POST",
        responseType: "Donation",
        requestType: "json",
        payloadType: "CreateDonation",
    },
    getDonationById: {
        path: "/api/api/donaciones/:id/",
        method: "GET",
        responseType: "Donation",
        requestType: null,
        payloadType: null,
    },
    replaceDonation: {
        path: "/api/api/donaciones/:id/",
        method: "PUT",
        responseType: "Donation",
        requestType: "json",
        payloadType: "ReplaceDonation",
    },
    updateDonation: {
        path: "/api/api/donaciones/:id/",
        method: "PATCH",
        responseType: "Donation",
        requestType: "json",
        payloadType: "UpdateDonation",
    },
    deleteDonation: {
        path: "/api/api/donaciones/:id/",
        method: "DELETE",
        responseType: "DeleteResponse",
        requestType: null,
        payloadType: null,
    },
    getMyDonations: {
        path: "/api/api/donaciones/mis_donaciones/",
        method: "GET",
        responseType: "MyDonations",
        requestType: null,
        payloadType: null,
    },

    // Evidences
    getEvidences: {
        path: "/api/api/evidencias/",
        method: "GET",
        responseType: "EvidenciaList",
        requestType: null,
        payloadType: null,
    },
    createEvidence: {
        path: "/api/api/evidencias/",
        method: "POST",
        responseType: "Evidencia",
        requestType: "json",
        payloadType: "CreateEvidencia",
    },
    getEvidenceById: {
        path: "/api/api/evidencias/:id/",
        method: "GET",
        responseType: "Evidencia",
        requestType: null,
        payloadType: null,
    },
    replaceEvidence: {
        path: "/api/api/evidencias/:id/",
        method: "PUT",
        responseType: "Evidencia",
        requestType: "json",
        payloadType: "ReplaceEvidencia",
    },
    updateEvidence: {
        path: "/api/api/evidencias/:id/",
        method: "PATCH",
        responseType: "Evidencia",
        requestType: "json",
        payloadType: "UpdateEvidencia",
    },
    deleteEvidence: {
        path: "/api/api/evidencias/:id/",
        method: "DELETE",
        responseType: "DeleteResponse",
        requestType: null,
        payloadType: null,
    },

    // Conversations
    getConversations: {
        path: "/api/api/conversaciones/",
        method: "GET",
        responseType: "ConversacionList",
        requestType: null,
        payloadType: null,
    },
    createConversation: {
        path: "/api/api/conversaciones/",
        method: "POST",
        responseType: "Conversacion",
        requestType: "json",
        payloadType: "CreateConversacion",
    },
    getConversationById: {
        path: "/api/api/conversaciones/:id/",
        method: "GET",
        responseType: "Conversacion",
        requestType: null,
        payloadType: null,
    },
    replaceConversation: {
        path: "/api/api/conversaciones/:id/",
        method: "PUT",
        responseType: "Conversacion",
        requestType: "json",
        payloadType: "ReplaceConversacion",
    },
    updateConversation: {
        path: "/api/api/conversaciones/:id/",
        method: "PATCH",
        responseType: "Conversacion",
        requestType: "json",
        payloadType: "UpdateConversacion",
    },
    deleteConversation: {
        path: "/api/api/conversaciones/:id/",
        method: "DELETE",
        responseType: "DeleteResponse",
        requestType: null,
        payloadType: null,
    },

    // Messages
    getMessages: {
        path: "/api/api/mensajes/",
        method: "GET",
        responseType: "MensajeList",
        requestType: null,
        payloadType: null,
    },
    createMessage: {
        path: "/api/api/mensajes/",
        method: "POST",
        responseType: "Mensaje",
        requestType: "json",
        payloadType: "CreateMensaje",
    },
    getMessageById: {
        path: "/api/api/mensajes/:id/",
        method: "GET",
        responseType: "Mensaje",
        requestType: null,
        payloadType: null,
    },
    replaceMessage: {
        path: "/api/api/mensajes/:id/",
        method: "PUT",
        responseType: "Mensaje",
        requestType: "json",
        payloadType: "ReplaceMensaje",
    },
    updateMessage: {
        path: "/api/api/mensajes/:id/",
        method: "PATCH",
        responseType: "Mensaje",
        requestType: "json",
        payloadType: "UpdateMensaje",
    },
    deleteMessage: {
        path: "/api/api/mensajes/:id/",
        method: "DELETE",
        responseType: "DeleteResponse",
        requestType: null,
        payloadType: null,
    },

    // Moderation reports
    getReports: {
        path: "/api/api/reportes/",
        method: "GET",
        responseType: "ReporteList",
        requestType: null,
        payloadType: null,
    },
    createReport: {
        path: "/api/api/reportes/",
        method: "POST",
        responseType: "Reporte",
        requestType: "json",
        payloadType: "CreateReporte",
    },
    getReportById: {
        path: "/api/api/reportes/:id/",
        method: "GET",
        responseType: "Reporte",
        requestType: null,
        payloadType: null,
    },
    replaceReport: {
        path: "/api/api/reportes/:id/",
        method: "PUT",
        responseType: "Reporte",
        requestType: "json",
        payloadType: "ReplaceReporte",
    },
    updateReport: {
        path: "/api/api/reportes/:id/",
        method: "PATCH",
        responseType: "Reporte",
        requestType: "json",
        payloadType: "UpdateReporte",
    },
    deleteReport: {
        path: "/api/api/reportes/:id/",
        method: "DELETE",
        responseType: "DeleteResponse",
        requestType: null,
        payloadType: null,
    },

    // Sanctions
    getSanctions: {
        path: "/api/api/sanciones/",
        method: "GET",
        responseType: "SancionList",
        requestType: null,
        payloadType: null,
    },
    createSanction: {
        path: "/api/api/sanciones/",
        method: "POST",
        responseType: "Sancion",
        requestType: "json",
        payloadType: "CreateSancion",
    },
    getSanctionById: {
        path: "/api/api/sanciones/:id/",
        method: "GET",
        responseType: "Sancion",
        requestType: null,
        payloadType: null,
    },
    replaceSanction: {
        path: "/api/api/sanciones/:id/",
        method: "PUT",
        responseType: "Sancion",
        requestType: "json",
        payloadType: "ReplaceSancion",
    },
    updateSanction: {
        path: "/api/api/sanciones/:id/",
        method: "PATCH",
        responseType: "Sancion",
        requestType: "json",
        payloadType: "UpdateSancion",
    },
    deleteSanction: {
        path: "/api/api/sanciones/:id/",
        method: "DELETE",
        responseType: "DeleteResponse",
        requestType: null,
        payloadType: null,
    },

    // OCR
    getOcrDocuments: {
        path: "/api/api/documentos-ocr/",
        method: "GET",
        responseType: "DocumentoOCRList",
        requestType: null,
        payloadType: null,
    },
    createOcrDocument: {
        path: "/api/api/documentos-ocr/",
        method: "POST",
        responseType: "DocumentoOCR",
        requestType: "json",
        payloadType: "CreateDocumentoOCR",
    },
    getOcrDocumentById: {
        path: "/api/api/documentos-ocr/:id/",
        method: "GET",
        responseType: "DocumentoOCR",
        requestType: null,
        payloadType: null,
    },
    replaceOcrDocument: {
        path: "/api/api/documentos-ocr/:id/",
        method: "PUT",
        responseType: "DocumentoOCR",
        requestType: "json",
        payloadType: "ReplaceDocumentoOCR",
    },
    updateOcrDocument: {
        path: "/api/api/documentos-ocr/:id/",
        method: "PATCH",
        responseType: "DocumentoOCR",
        requestType: "json",
        payloadType: "UpdateDocumentoOCR",
    },
    deleteOcrDocument: {
        path: "/api/api/documentos-ocr/:id/",
        method: "DELETE",
        responseType: "DeleteResponse",
        requestType: null,
        payloadType: null,
    },
    uploadAndProcessOcrDocument: {
        path: "/api/api/documentos-ocr/subir-y-procesar/",
        method: "POST",
        responseType: "DocumentoOCRProcessResponse",
        requestType: "formData",
        payloadType: "UploadDocumentoOCR",
    },
    getOcrLogs: {
        path: "/api/api/logs-ocr/",
        method: "GET",
        responseType: "LogOCRList",
        requestType: null,
        payloadType: null,
    },
    getOcrLogById: {
        path: "/api/api/logs-ocr/:id/",
        method: "GET",
        responseType: "LogOCR",
        requestType: null,
        payloadType: null,
    },

    // Catalogs
    getCaseStates: {
        path: "/api/api/estados-caso/",
        method: "GET",
        responseType: "EstadoCasoList",
        requestType: null,
        payloadType: null,
    },
    getCaseStateById: {
        path: "/api/api/estados-caso/:id/",
        method: "GET",
        responseType: "EstadoCaso",
        requestType: null,
        payloadType: null,
    },
    getOcrStates: {
        path: "/api/api/estados-ocr/",
        method: "GET",
        responseType: "EstadoOCRList",
        requestType: null,
        payloadType: null,
    },
    getOcrStateById: {
        path: "/api/api/estados-ocr/:id/",
        method: "GET",
        responseType: "EstadoOCR",
        requestType: null,
        payloadType: null,
    },
    getReportStates: {
        path: "/api/api/estados-reporte/",
        method: "GET",
        responseType: "EstadoReporteList",
        requestType: null,
        payloadType: null,
    },
    getReportStateById: {
        path: "/api/api/estados-reporte/:id/",
        method: "GET",
        responseType: "EstadoReporte",
        requestType: null,
        payloadType: null,
    },
    getMessageTypes: {
        path: "/api/api/tipos-mensaje/",
        method: "GET",
        responseType: "TipoMensajeList",
        requestType: null,
        payloadType: null,
    },
    getMessageTypeById: {
        path: "/api/api/tipos-mensaje/:id/",
        method: "GET",
        responseType: "TipoMensaje",
        requestType: null,
        payloadType: null,
    },
    getSanctionTypes: {
        path: "/api/api/tipos-sancion/",
        method: "GET",
        responseType: "TipoSancionList",
        requestType: null,
        payloadType: null,
    },
    getSanctionTypeById: {
        path: "/api/api/tipos-sancion/:id/",
        method: "GET",
        responseType: "TipoSancion",
        requestType: null,
        payloadType: null,
    },
    getCatalogUserTypes: {
        path: "/api/api/tipos-usuario/",
        method: "GET",
        responseType: "TipoUsuarioList",
        requestType: null,
        payloadType: null,
    },
    getCatalogUserTypeById: {
        path: "/api/api/tipos-usuario/:id/",
        method: "GET",
        responseType: "TipoUsuario",
        requestType: null,
        payloadType: null,
    },
} as const satisfies Record<string, EndpointDef>;

export type EndpointName = keyof typeof ENDPOINTS;
